export const MAP_HOTSPOT_DEBUG = false;

export const MAP_HOTSPOTS = [
  {
    id: 'house',
    type: 'rect',
    x: 62,
    y: 57,
    width: 31,
    height: 20,
    scene: 'house',
    action: 'open:house',
    labelKey: 'zoneHouse',
    actionKey: 'openHouse',
  },
  {
    id: 'garden',
    type: 'rect',
    x: 82,
    y: 78,
    width: 28,
    height: 22,
    scene: 'garden',
    action: 'open:garden',
    labelKey: 'zoneGarden',
    actionKey: 'openGarden',
  },
  {
    id: 'canal',
    type: 'ellipse',
    x: 36,
    y: 28,
    width: 49,
    height: 36,
    scene: 'canal',
    action: 'open:canal',
    labelKey: 'zoneCanal',
    actionKey: 'openPond',
  },
  {
    id: 'sluice',
    type: 'ellipse',
    x: 8,
    y: 34,
    width: 20,
    height: 16,
    scene: 'sluice',
    action: 'mapWater:sluice',
    labelKey: 'zoneSluice',
    actionKey: 'zoneSluice',
    direction: 'left',
    labelX: 13,
    labelY: 31,
  },
  {
    id: 'greada',
    type: 'ellipse',
    x: 10,
    y: 10,
    width: 18,
    height: 14,
    scene: 'greada',
    action: 'open:greada',
    labelKey: 'zoneGreada',
    actionKey: 'zoneGreada',
    direction: 'left',
  },
  {
    id: 'fire_ponds',
    type: 'ellipse',
    x: 91,
    y: 36,
    width: 19,
    height: 18,
    scene: 'fire_ponds',
    action: 'mapWater:fire_ponds',
    labelKey: 'zoneFirePonds',
    actionKey: 'zoneFirePonds',
    direction: 'right',
    labelX: 86,
    labelY: 33,
  },
  {
    id: 'cafe',
    type: 'ellipse',
    x: 50,
    y: 68,
    width: 22,
    height: 16,
    scene: 'cafe',
    action: 'open:cafe',
    labelKey: 'zoneCafe',
    actionKey: 'openCafe',
    labelX: 54,
    labelY: 63,
  },
  {
    id: 'market',
    type: 'ellipse',
    x: 25,
    y: 81,
    width: 26,
    height: 17,
    scene: 'market',
    action: 'open:market',
    labelKey: 'zoneMarket',
    actionKey: 'openMarket',
    labelX: 23,
    labelY: 84,
  },
  {
    id: 'bus_station',
    type: 'ellipse',
    x: 20,
    y: 56,
    width: 22,
    height: 15,
    scene: 'bus_station',
    action: 'open:bus_station',
    labelKey: 'zoneBusStation',
    actionKey: 'openBusStation',
    labelX: 17,
    labelY: 51,
  },
];
