export const MAP_HOTSPOTS = [
  {
    id: 'house',
    type: 'rect',
    x: 56,
    y: 54,
    width: 19,
    height: 16,
    scene: 'house',
    labelKey: 'zoneHouse',
    actionKey: 'openHouse',
  },
  {
    id: 'garden',
    type: 'rect',
    x: 63,
    y: 67,
    width: 20,
    height: 17,
    scene: 'garden',
    labelKey: 'zoneGarden',
    actionKey: 'openGarden',
  },
  {
    id: 'pond',
    type: 'rect',
    x: 29,
    y: 43,
    width: 21,
    height: 53,
    scene: 'pond',
    labelKey: 'zonePond',
    actionKey: 'openPond',
  },
  {
    id: 'market',
    type: 'ellipse',
    x: 31,
    y: 71,
    width: 29,
    height: 23,
    scene: 'market',
    labelKey: 'zoneMarket',
    actionKey: 'openMarket',
  },
];
