export const MAP_HOTSPOTS = [
  {
    id: 'house',
    type: 'rect',
    x: 56,
    y: 54,
    width: 19,
    height: 16,
    scene: 'house',
    labelKey: 'zoneHouse',
    actionKey: 'openHouse',
  },
  {
    id: 'garden',
    type: 'rect',
    x: 63,
    y: 67,
    width: 20,
    height: 17,
    scene: 'garden',
    labelKey: 'zoneGarden',
    actionKey: 'openGarden',
  },
  {
    id: 'fishing_select',
    type: 'ellipse',
    x: 34,
    y: 34,
    width: 28,
    height: 20,
    scene: 'fishing_select',
    labelKey: 'mapFishing',
    actionKey: 'openFishingSelect',
  },
  {
    id: 'market',
    type: 'ellipse',
    x: 31,
    y: 55,
    width: 28,
    height: 19,
    scene: 'market',
    labelKey: 'zoneMarket',
    actionKey: 'openMarket',
  },
  {
    id: 'bus_station',
    type: 'ellipse',
    x: 32,
    y: 71,
    width: 25,
    height: 17,
    scene: 'bus_station',
    labelKey: 'zoneBusStation',
    actionKey: 'openBusStation',
  },
];
